version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "quarterly"
      time: "08:00"
      timezone: Asia/Shanghai
    groups:
      github-actions:
        patterns:
          - "*"

  - package-ecosystem: cargo
    directory: "/"
    schedule:
      interval: "quarterly"
      time: "08:00"
      timezone: Asia/Shanghai
    groups:
      cargo-dependencies:
        patterns:
          - "*"
        update-types:
          - patch

  - package-ecosystem: npm
    directory: "/ui"
    schedule:
      interval: "quarterly"
      time: "08:00"
      timezone: Asia/Shanghai
    groups:
      npm-dependencies:
        patterns:
          - "*"
        update-types:
          - patch
