[package]
name = "yoin"
version = "0.1.0"
edition = "2024"

[workspace]
members = [".", "migration"]

[workspace.dependencies]
migration = { path = "migration" }
dotenvy = "0.15.7"
sea-orm = "2.0.0-rc"
sea-orm-migration = { version = "2.0.0-rc" }
tokio = "1.48.0"
serde = "1.0.228"
envy = "0.4.2"
tracing = "0.1.44"
tracing-subscriber = "0.3.22"
axum = "0.8.8"
serde_json = "1.0.148"

[dependencies]
tower-http = { version = "0.6.8", features = ["trace"] }
migration.workspace = true
dotenvy.workspace = true
envy.workspace = true
serde = { workspace = true, features = ["derive"] }
tokio = { workspace = true, features = ["macros", "rt"] }
tracing.workspace = true
tracing-subscriber = { workspace = true, features = [
  "env-filter",
  "local-time",
] }
sea-orm.workspace = true
axum.workspace = true
serde_json.workspace = true
thiserror = "2.0.17"

[features]
sqlite = ["migration/sqlite"]
mysql = ["migration/mysql"]
postgres = ["migration/postgres"]

[profile.release]
lto = true
codegen-units = 1
panic = "abort"
strip = true
opt-level = "z"
