//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use migration::enums::CommentStatus;
use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(table_name = "comments")]
pub struct Model {
  #[sea_orm(primary_key)]
  pub id: i64,
  pub user_id: i64,
  pub site_id: i64,
  pub path: String,
  pub content: String,
  pub status: CommentStatus,
  pub nick: String,
  pub link: String,
  pub email: String,
  pub created_at: DateTime,
  pub updated_at: DateTime,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
