//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use migration::enums::CommentStatus;
use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(table_name = "comments")]
pub struct Model {
  #[sea_orm(primary_key)]
  pub id: i64,
  pub user_id: Option<i64>,
  pub site_id: i64,
  pub thread_id: Option<i64>,
  pub parent_id: Option<i64>,
  pub page_path: String,
  pub content: String,
  pub status: CommentStatus,
  pub nickname: String,
  pub link: String,
  pub email: String,
  pub device: String,
  pub location: String,
  pub is_sticky: bool,
  pub up_vote: i32,
  pub down_vote: i32,
  pub created_at: DateTime,
  pub updated_at: DateTime,
  pub deleted_at: Option<DateTime>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
