//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use migration::enums::CommentSubscriptionEventType;
use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(table_name = "comment_subscriptions")]
pub struct Model {
  #[sea_orm(primary_key)]
  pub id: i64,
  pub site_id: i64,
  pub page_path: String,
  pub event_type: CommentSubscriptionEventType,
  pub user_id: Option<i64>,
  pub email: Option<String>,
  pub is_active: bool,
  pub created_at: DateTime,
  pub updated_at: DateTime,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
