//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(table_name = "moderation_providers")]
pub struct Model {
  #[sea_orm(primary_key)]
  pub id: i64,
  pub site_id: i64,
  pub provider: String,
  pub enabled: bool,
  pub model: String,
  pub api_base: String,
  pub api_key: String,
  pub prompt: Option<String>,
  pub created_at: DateTime,
  pub updated_at: DateTime,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
