//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use migration::enums::ModerationProviderType;
use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize, FromJsonQueryResult)]
#[serde(untagged)]
pub enum ModerationProviderConfig {
  LLM {
    model: String,
    api_base: String,
    api_key: String,
    #[serde(default)]
    rule: String,
  },
  AKISMET {
    api_key: String,
    blog_url: String,
  },
}

#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(table_name = "moderation_providers")]
pub struct Model {
  #[sea_orm(primary_key)]
  pub id: i64,
  pub site_id: i64,
  pub provider_kind: ModerationProviderType,
  pub enabled: bool,
  pub config: ModerationProviderConfig,
  pub created_at: DateTime,
  pub updated_at: DateTime,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
