//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(table_name = "oauth_providers")]
pub struct Model {
  #[sea_orm(primary_key)]
  pub id: i64,
  pub site_id: Option<i64>,
  pub enabled: bool,
  pub provider_code: String,
  pub client_id: String,
  pub client_secret: String,
  pub redirect_uri: String,
  pub created_at: DateTime,
  pub updated_at: DateTime,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
