//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

pub use super::{
  comment_subscriptions::Entity as CommentSubscriptions,
  comments::Entity as Comments,
  moderation_providers::Entity as ModerationProviders,
  oauth_providers::Entity as OauthProviders,
  permissions::Entity as Permissions,
  reactions::Entity as Reactions,
  role_permissions::Entity as RolePermissions,
  roles::Entity as Roles,
  sites::Entity as Sites,
  user_identities::Entity as UserIdentities,
  user_role_bindings::Entity as UserRoleBindings,
  users::Entity as Users,
};
