//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use migration::enums::{ReactionActorType, ReactionTargetType};
use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(table_name = "reactions")]
pub struct Model {
  #[sea_orm(primary_key)]
  pub id: i64,
  pub site_id: i64,
  pub target_type: ReactionTargetType,
  pub comment_id: Option<i64>,
  pub page_path: String,
  pub actor_type: ReactionActorType,
  pub actor_id: String,
  pub r#type: String,
  pub target_key: String,
  pub created_at: DateTime,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
