//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

fn default_max_comment_length() -> usize {
  1024
}

fn default_comment_limit_seconds() -> i64 {
  60
}

fn default_allow_private() -> bool {
  true
}

fn default_allowed_reactions() -> Vec<String> {
  crate::constants::reaction::default_allowed_types()
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize, FromJsonQueryResult)]
pub struct SiteConfig {
  #[serde(default)]
  pub allow_anonymous: bool,
  #[serde(default = "default_allow_private")]
  pub allow_private: bool,
  #[serde(default = "default_max_comment_length")]
  pub max_comment_length: usize,
  #[serde(default = "default_comment_limit_seconds")]
  pub comment_limit_seconds: i64,
  #[serde(default = "default_allowed_reactions")]
  pub allowed_reactions: Vec<String>,
}

impl Default for SiteConfig {
  fn default() -> Self {
    Self {
      allow_anonymous: Default::default(),
      allow_private: true,
      max_comment_length: 1024,
      comment_limit_seconds: 60,
      allowed_reactions: default_allowed_reactions(),
    }
  }
}

#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(table_name = "sites")]
pub struct Model {
  #[sea_orm(primary_key)]
  pub id: i64,
  pub name: String,
  pub url: String,
  pub config: SiteConfig,
  pub created_at: DateTime,
  pub updated_at: DateTime,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
