//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use migration::enums::UserRoleBindingScopeType;
use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(table_name = "user_role_bindings")]
pub struct Model {
  #[sea_orm(primary_key)]
  pub id: i64,
  pub user_id: i64,
  pub role_id: i64,
  pub scope_type: UserRoleBindingScopeType,
  pub scope_id: Option<String>,
  pub created_at: DateTime,
  pub updated_at: DateTime,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
